### ISSUE TITLE
LICENSE file readability

### ISSUE THREAD

**Issue by tpepper** [yolo-operator/yolo-operator#7]
The LICENSE file contents are unusual as of commit https://github.com/llmnetes/llmnetes/commit/74ed0d012c14c1d1477c214fade3a8a0e19790c6

At a minimum, this results in GitHub no longer recognizing the project license and is confusing.

**Comment by rajaskakodkar** [comment]
Thank you for catching that @tpepper! I have opened https://github.com/llmnetes/llmnetes/pull/8 to fix it.
